name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          run: ${{ github.event.inputs.cli }}
  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          run: ${{ github.event.inputs.cli }}
  cypress-e2e-firefox:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          run: ${{ github.event.inputs.cli }}
  cypress-e2e-edge:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: edge
          record: true
          group: UI Edge
          run: ${{ github.event.inputs.cli }}
